name: Deploying to EC2 Instance
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  remote_command: 
    runs-on: ubuntu-latest     
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Run remote command via SSH
      uses: D3rHase/ssh-command-action@latest
      with:
          StrictHostKeyChecking: 'no'
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          user: ${{ secrets.USER }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          host_fingerprint: ${{ secrets.HOST_FINGERPRINT }}
          command: |
            echo "Connected successfully, running commands now"
            git -C lms_backend pull
            forever restart lms_backend/src/index.js
            
